# Generated by Django 4.1 on 2024-02-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Description', models.TextField()),
                ('Category', models.TextField(choices=[('GAMING', 'gaming'), ('FURNITURE', 'furniture'), ('EDUCATION', 'educaiton'), ('DAILY NEEDS', 'daily needs'), ('FASHION', 'fashion')])),
                ('Condition', models.TextField(choices=[('new', 'new'), ('good', 'as good as new'), ('average', 'slightly used'), ('poor', 'extremely used')])),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
