# Generated by Django 4.1 on 2024-08-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('report_file', models.FileField(upload_to='medical_reports/')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
