# Generated by Django 4.1 on 2024-08-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_medicalreport_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='report_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
